/**
 * CaseRow — a single test case's status row.
 *
 * Renders with status icon + text label (colour-blind safe — never
 * green/red only). When the row has resolved (passed / failed /
 * skipped), it shows a collapsible inline log with the case's response
 * status, message, and response body. A "View evidence" link points
 * at the per-case evidence log served by the v2.1 server at
 * `GET /api/runs/:id/evidence/:caseId` (MAS-302).
 *
 * No false-green UX: a `failed` outcome is rendered as red, never as
 * "passed". Pending/running rows are visually distinct (dashed border,
 * muted colour) so an in-progress run cannot be mistaken for a green pass.
 *
 * Role tinting: a small role badge sits in the meta row when `role` is
 * provided. The accent colour follows the role taxonomy in
 * `lib/roles.ts` — cyan (issuer), magenta (verifier), lime (wallet). The
 * badge is also a small left-border tint on the row, so the role reads
 * at a glance from the listing.
 *
 * runId is required for the evidence link. When omitted (e.g. some
 * tests render a row in isolation), the evidence link is hidden — the
 * inline log is still visible.
 */

import { useState } from 'react';
import type { CaseRow as CaseRowData } from '../lib/types';
import { STATUS_ICON, STATUS_LABEL } from '../lib/types';
import type { PrimaryRole } from '../lib/roles';
import { resolveRoleForCase } from '../lib/roles';
import { api } from '../lib/api';

export interface CaseRowProps {
  case: CaseRowData;
  /** Optional role classification for the badge + left tint. If
   *  omitted, the component looks it up from the case-id → role map
   *  generated by `scripts/refresh-case-roles.sh`. */
  role?: PrimaryRole;
  /** The run id. Required to render the "View evidence" link. The link
   *  is hidden when this is omitted. */
  runId?: string;
}

function formatDuration(ms?: number): string {
  if (ms === undefined) return '–';
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function statusClass(outcome: CaseRowData['outcome']): string {
  return `status ${outcome}`;
}

function roleAccentClass(role: PrimaryRole): string {
  return `case-row has-role role-${role}`;
}

const ROLE_BADGE_LABEL: Record<PrimaryRole, string> = {
  issuer: 'Issuer',
  verifier: 'Verifier',
  wallet: 'Wallet',
};

function outcomeClass(outcome: CaseRowData['outcome']): string {
  switch (outcome) {
    case 'failed':
      return 'is-failed';
    case 'passed':
      return 'is-passed';
    case 'skipped':
      return 'is-skipped';
    case 'running':
      return 'is-running';
    case 'pending':
    default:
      return 'is-pending';
  }
}

export function CaseRow({ case: c, role: roleProp, runId }: CaseRowProps): JSX.Element {
  const [copied, setCopied] = useState(false);
  const role = roleProp ?? resolveRoleForCase(c.id);
  const ariaLabel = role
    ? `${STATUS_LABEL[c.outcome]}: ${c.id} (${ROLE_BADGE_LABEL[role]} role)`
    : `${STATUS_LABEL[c.outcome]}: ${c.id}`;

  const isResolved = c.outcome === 'passed' || c.outcome === 'failed' || c.outcome === 'skipped';
  const hasMessage = Boolean(c.message);
  const hasBody = c.responseBody !== undefined;
  const hasStatus = c.responseStatus !== undefined;
  const hasEvidence = c.evidence !== undefined;
  const hasLog = isResolved && (hasMessage || hasBody || hasStatus || hasEvidence);
  const showEvidence = Boolean(runId) && isResolved;

  const onCopy = async (): Promise<void> => {
    try {
      // Prefer copying the full transaction (request line + status + body)
      // when structured evidence is available; fall back to the raw
      // response body so the legacy copy-on-failed path still works.
      let text = '';
      if (c.evidence) {
        const ev = c.evidence;
        text =
          `${ev.request.method} ${ev.request.url}\n` +
          `HTTP ${ev.response.status}\n` +
          (ev.mock === true ? '(in-process mock)\n' : '') +
          JSON.stringify(ev.response.body, null, 2);
      } else if (c.responseBody !== undefined) {
        text = JSON.stringify(c.responseBody, null, 2);
      }
      if (text) {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }
    } catch {
      // clipboard unavailable; silently ignore — copy is a nice-to-have
    }
  };

  const rowClass = [
    'case-row',
    outcomeClass(c.outcome),
    role ? roleAccentClass(role) : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <li
      className={rowClass}
      data-testid={`case-row-${c.id}`}
      data-role={role ?? undefined}
      data-outcome={c.outcome}
      aria-label={ariaLabel}
    >
      <span className={statusClass(c.outcome)} aria-hidden="true">
        {STATUS_ICON[c.outcome]}
      </span>
      <div className="case-row-main">
        <div className="case-row-head">
          <span className="id">{c.id}</span>
          {c.name ? <span className="name"> — {c.name}</span> : null}
          {role ? (
            <span
              className={`role-badge role-${role}`}
              data-testid={`role-badge-${c.id}`}
              aria-hidden="true"
              title={`${ROLE_BADGE_LABEL[role]} role`}
            >
              {ROLE_BADGE_LABEL[role]}
            </span>
          ) : null}
        </div>
        {hasLog ? (
          <details
            className="case-log"
            data-testid={`case-log-${c.id}`}
            open={c.outcome === 'failed'}
          >
            <summary data-testid={`case-log-summary-${c.id}`}>
              <span className="case-log-label">
                {c.outcome === 'failed' ? 'Failure log' : c.outcome === 'skipped' ? 'Skip log' : 'Run log'}
              </span>
              {hasStatus ? (
                <span className="case-log-status">HTTP {c.responseStatus}</span>
              ) : null}
            </summary>
            <div className="case-log-body" data-testid={`case-log-body-${c.id}`}>
              {hasMessage ? (
                <p className="case-log-message" data-testid={`case-log-message-${c.id}`}>
                  {c.message}
                </p>
              ) : null}
              {hasEvidence ? (
                <>
                  <p
                    className="case-log-request"
                    data-testid={`case-log-request-${c.id}`}
                  >
                    <span className="case-log-method">
                      {c.evidence?.request.method}
                    </span>{' '}
                    <span className="case-log-url">{c.evidence?.request.url}</span>
                    {c.evidence?.mock === true ? (
                      <span
                        className="case-log-mock"
                        data-testid={`case-log-mock-${c.id}`}
                      >
                        {' '}in-process mock
                      </span>
                    ) : null}
                  </p>
                  <pre data-testid={`case-log-response-${c.id}`}>
                    {JSON.stringify(c.evidence?.response.body, null, 2)}
                  </pre>
                </>
              ) : hasBody ? (
                <pre data-testid={`case-log-response-${c.id}`}>
                  {JSON.stringify(c.responseBody, null, 2)}
                </pre>
              ) : null}
            </div>
          </details>
        ) : null}
      </div>
      {c.outcome === 'failed' && c.responseBody !== undefined ? (
        <div className="meta-row">
          {c.responseStatus !== undefined ? <span>HTTP {c.responseStatus}</span> : null}
          <button
            type="button"
            className="btn btn-ghost"
            onClick={onCopy}
            aria-label={`Copy response body for ${c.id}`}
          >
            {copied ? 'Copied' : 'Copy body'}
          </button>
        </div>
      ) : (
        <span className="op">{c.operation ?? ''}</span>
      )}
      <div className="case-row-aside">
        {showEvidence ? (
          <a
            className="btn btn-ghost evidence-link"
            href={api.evidenceUrl(runId as string, c.id)}
            data-testid={`case-evidence-${c.id}`}
            title={`Download evidence log for ${c.id}`}
            download={`evidence-${runId}-${c.id}.log`}
          >
            Evidence
          </a>
        ) : null}
        <span className="duration">{formatDuration(c.durationMs)}</span>
      </div>
    </li>
  );
}
