/**
 * CaseRow — a single test case's status row.
 *
 * Renders with status icon + text label (colour-blind safe — never
 * green/red only). When the row is a failure, shows the failing
 * assertion + a copyable response body in a code block.
 *
 * No false-green UX: a `failed` outcome is rendered as red, never as
 * "passed". Pending/running rows are visually distinct (dashed border,
 * muted colour) so an in-progress run cannot be mistaken for a green pass.
 *
 * Role tinting: a small role badge sits in the meta row when `role` is
 * provided. The accent colour follows the role taxonomy in
 * `lib/roles.ts` — cyan (issuer), magenta (verifier), lime (wallet). The
 * badge is also a small left-border tint on the row, so the role reads
 * at a glance from the listing.
 */

import { useState } from 'react';
import type { CaseRow as CaseRowData } from '../lib/types';
import { STATUS_ICON, STATUS_LABEL } from '../lib/types';
import type { PrimaryRole } from '../lib/roles';
import { resolveRoleForCase } from '../lib/roles';

export interface CaseRowProps {
  case: CaseRowData;
  /** Optional role classification for the badge + left tint. If
   *  omitted, the component looks it up from the case-id → role map
   *  generated by `scripts/refresh-case-roles.sh`. */
  role?: PrimaryRole;
}

function formatDuration(ms?: number): string {
  if (ms === undefined) return '–';
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(2)}s`;
}

function statusClass(outcome: CaseRowData['outcome']): string {
  return `status ${outcome}`;
}

function roleAccentClass(role: PrimaryRole): string {
  return `case-row has-role role-${role}`;
}

const ROLE_BADGE_LABEL: Record<PrimaryRole, string> = {
  issuer: 'Issuer',
  verifier: 'Verifier',
  wallet: 'Wallet',
};

export function CaseRow({ case: c, role: roleProp }: CaseRowProps): JSX.Element {
  const [copied, setCopied] = useState(false);
  const role = roleProp ?? resolveRoleForCase(c.id);
  const ariaLabel = role
    ? `${STATUS_LABEL[c.outcome]}: ${c.id} (${ROLE_BADGE_LABEL[role]} role)`
    : `${STATUS_LABEL[c.outcome]}: ${c.id}`;

  const onCopy = async (): Promise<void> => {
    try {
      const text = c.responseBody !== undefined ? JSON.stringify(c.responseBody, null, 2) : '';
      if (text) {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
      }
    } catch {
      // clipboard unavailable; silently ignore — copy is a nice-to-have
    }
  };

  const rowClass = [
    'case-row',
    c.outcome === 'failed' ? 'is-failed' : '',
    role ? roleAccentClass(role) : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <li
      className={rowClass}
      data-testid={`case-row-${c.id}`}
      data-role={role ?? undefined}
      aria-label={ariaLabel}
    >
      <span className={statusClass(c.outcome)} aria-hidden="true">
        {STATUS_ICON[c.outcome]}
      </span>
      <div>
        <span className="id">{c.id}</span>
        {c.name ? <span className="name"> — {c.name}</span> : null}
        {role ? (
          <span
            className={`role-badge role-${role}`}
            data-testid={`role-badge-${c.id}`}
            aria-hidden="true"
            title={`${ROLE_BADGE_LABEL[role]} role`}
          >
            {ROLE_BADGE_LABEL[role]}
          </span>
        ) : null}
        {c.outcome === 'failed' ? (
          <div className="body" data-testid={`case-body-${c.id}`}>
            {c.message ?? 'assertion mismatch'}
            {c.responseStatus !== undefined ? (
              <>
                {'\n'}Response status: {c.responseStatus}
              </>
            ) : null}
            {c.responseBody !== undefined ? (
              <pre data-testid={`case-response-${c.id}`}>
                {JSON.stringify(c.responseBody, null, 2)}
              </pre>
            ) : null}
          </div>
        ) : null}
      </div>
      {c.outcome === 'failed' ? (
        <div className="meta-row">
          {c.responseStatus !== undefined ? (
            <span>HTTP {c.responseStatus}</span>
          ) : null}
          {c.responseBody !== undefined ? (
            <button
              type="button"
              className="btn btn-ghost"
              onClick={onCopy}
              aria-label={`Copy response body for ${c.id}`}
            >
              {copied ? 'Copied' : 'Copy body'}
            </button>
          ) : null}
        </div>
      ) : (
        <span className="op">{c.operation ?? ''}</span>
      )}
      <span className="duration">{formatDuration(c.durationMs)}</span>
    </li>
  );
}
